defmodule RunlocalWeb.Endpoint do
  use Phoenix.Endpoint, otp_app: :runlocal

  # The session will be stored in the cookie and signed,
  # this means its contents can be read but not tampered with.
  # Set :encryption_salt if you would also like to encrypt it.
  @session_options [
    store: :cookie,
    key: "_runlocal_key",
    signing_salt: "qhBYONiN",
    same_site: "Lax"
  ]

  socket "/tunnel", RunlocalWeb.TunnelSocket,
    websocket: [timeout: :infinity, max_frame_size: 11_000_000, connect_info: [:peer_data, :x_headers]]

  # Serve at "/" the static files from "priv/static" directory.
  #
  # When code reloading is disabled (e.g., in production),
  # the `gzip` option is enabled to serve compressed
  # static files generated by running `phx.digest`.
  plug Plug.Static,
    at: "/",
    from: :runlocal,
    gzip: not code_reloading?,
    only: RunlocalWeb.static_paths(),
    raise_on_missing_only: code_reloading?

  # Code reloading can be explicitly enabled under the
  # :code_reloader configuration of your endpoint.
  if code_reloading? do
    socket "/phoenix/live_reload/socket", Phoenix.LiveReloader.Socket
    plug Phoenix.LiveReloader
    plug Phoenix.CodeReloader
  end

  plug Plug.RequestId
  plug Plug.Telemetry, event_prefix: [:phoenix, :endpoint]

  plug Plug.Parsers,
    parsers: [:urlencoded, :multipart, :json],
    pass: ["*/*"],
    json_decoder: Phoenix.json_library()

  plug Plug.MethodOverride
  plug Plug.Head
  plug RunlocalWeb.Plugs.SubdomainRouter
  plug Plug.Session, @session_options
  plug RunlocalWeb.Router
end
